FROM python:3.12-alpine

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
  && pip install --no-cache-dir --upgrade pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./requirements.txt /app/
RUN pip3 install -r /app/requirements.txt
COPY . /app/

EXPOSE 8000

CMD [ "python3", "main.py"]