FROM golang:1.26.0-alpine3.23 AS builder

WORKDIR /build
COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app

FROM alpine:3.21 AS final

COPY --from=builder /app /bin/app

EXPOSE 8001

CMD ["/bin/app"]
